#!/usr/bin/env node
/**
 * npm run db:import — copies a card catalog JSON file into Supabase.
 *
 *   npm run db:import -- cards.json           sends the file to Supabase (needs .env)
 *   npm run db:import -- cards.json --sql     writes a new migration in supabase/migrations/
 *                                             instead (no .env needed): the Supabase GitHub
 *                                             integration applies it after a push on main
 *
 * The file has the format written by `npm run sync -- --json cards.json`:
 * { generatedAt, popularity, license, cards: [...] }. Cards are added or
 * updated by id; cards already in the database that are not in the file are kept.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { cardToRow } from '../server/catalog.js';
import { openStore } from './supabase-env.js';

const args = process.argv.slice(2);
const asSql = args.includes('--sql');
const file = args.find((arg) => !arg.startsWith('--'));
if (!file) throw new Error('Usage: npm run db:import -- <cards.json> [--sql]');
const inputFile = resolve(file);
const stamp = new Date().toISOString().replace(/\D/g, '').slice(0, 14);
const SQL_FILE = `supabase/migrations/${stamp}_card_catalog.sql`;

const { generatedAt = null, popularity = null, license = null, cards } = JSON.parse(readFileSync(inputFile, 'utf8'));
if (!Array.isArray(cards) || cards.length === 0) throw new Error(`No cards in ${inputFile}`);
const ids = new Set();
for (const card of cards) {
  if (!card.id || !card.source) throw new Error(`A card has no id or source: ${JSON.stringify(card).slice(0, 80)}…`);
  if (ids.has(card.id)) throw new Error(`Two cards have the id "${card.id}"`);
  ids.add(card.id);
}

/** Dollar-quoted SQL literal of a value as jsonb (no escaping needed). */
function jsonLiteral(value, tag) {
  const json = JSON.stringify(value);
  if (json.includes(`$${tag}$`)) throw new Error(`The data contains $${tag}$`);
  return `$${tag}$${json}$${tag}$::jsonb`;
}

function toSql() {
  const columns = Object.keys(cardToRow({}));
  const list = columns.join(', ');
  const updates = [...columns.filter((c) => c !== 'id').map((c) => `${c} = excluded.${c}`), 'updated_at = now()'];
  return `-- Card catalog (${cards.length} cards), generated by "npm run db:import -- <file> --sql"
-- on ${new Date().toISOString()}. It can be run again.

insert into public.cards (${list})
select ${list}
from jsonb_populate_recordset(null::public.cards, ${jsonLiteral(cards.map(cardToRow), 'cards')})
on conflict (id) do update set
  ${updates.join(',\n  ')};

insert into public.catalog_info (id, generated_at, popularity, license)
select true, generated_at, popularity, license
from jsonb_populate_record(null::public.catalog_info, ${jsonLiteral({ generated_at: generatedAt, popularity, license }, 'info')})
on conflict (id) do update set
  generated_at = excluded.generated_at,
  popularity = excluded.popularity,
  license = excluded.license;
`;
}

if (asSql) {
  writeFileSync(new URL(`../${SQL_FILE}`, import.meta.url), toSql());
  console.log(`✔ Wrote ${cards.length} cards to ${SQL_FILE}: push it on main to apply it (or paste it in the SQL Editor).`);
} else {
  const store = openStore();
  await store.saveCatalog(cards, { generatedAt, popularity, license });
  const { cards: saved } = await store.loadCatalog();
  console.log(`✔ Sent ${cards.length} cards to Supabase (${saved.length} cards in the database).`);
}
